version: "3"

services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:  
        -   "8089:8089" 
    depends_on: 
        -   db 
    links: 
        - db
    volumes: 
        - .:/recordar
  db:
    build: 
      context: ./sql/
      dockerfile: Dockerfile
    restart: always
    image: recordar-psql 
    environment: 
        -   POSTGRES_USER=${RECORDAR_PSQL_USER}
        -   POSTGRES_PASSWORD=${RECORDAR_PSQL_PASSWORD}
        -   POSTGRES_PORT=${RECORDAR_PSQL_PORT}
        -   POSTGRES_DB=recordar
    container_name: "recordar_db"
    ports: 
        - "5430:5432"
